Revamped menu
technobly/VEXTREME pull request #73
Opened 2021-03-03 18:07 UTC by v-kiniv

### Problem

- Font is hard to read and ugly
- Navigation is cumbersome, no indication of where you at currently in the list
- LED is too bright and fleshy, there is no way to change brightness or completely turn it off
- No screen saver to protect CRT from burn-in

### Solution

- "Raster" based font replaced by vector font. It's drawn using optimized routines borrowed from Malban's source codes. Whole range of ASCII chars supported. Currently lower and upper case letters are the same, but the table made in such way that this can be changed easily in the future. Filename is cropped to 8 chars if not highlighted(can be adjusted in settings) to meet 30k cycles constrain.
- Page based list was replaced by continuous, however, you can still turn pages with left-right joystick. Scrollbar added to indicate position in the list.
- Added settings screen where you can adjust LED brightness and color.
- Added "Stars" screen saver, delay can be adjusted in settings. 

The settings screen implemented in such way, that its structure is not "hardcoded", for example you can add another mode for LED or add another submenu simply by adding another text line in `settings.i` file, no need to change implementation.

### Steps to Test

You'll need to compile and flash both STM32 firmware and menu.bin.

### References

Thanks to Malban for tutorials and fast drawing routines.
Thanks to C.Malcolm for "FAKE 3D STARFIELD" which was adapted as screen saver.

### Note
These PR contains a lot of changes and affect lines of code that is not directly related to the PR problem and solution.

All code was reformatted to follow next rules(I believe it's easier to navigate in code with consistent formatting):
- Label starts at column 0
- Instruction starts at column 2
- Instruction arguments starts at column 24
- Comment starts at column 45

A lot of literals(especially memory addresses) in STM firmware and cart was replaced by constants and offsets.

---

### Contributor License Agreement

I, Vasily Kiniv, agree to license my contributions to this project under the terms of the [MIT](https://opensource.org/licenses/MIT) or any later version.

p.s. I understand that I was suppose to use GPL license, but I think MIT in contrast to GPL is really free and open.

2021-03-04 22:49 UTC, technobly requested changes
Lots of great changes and improvements as far as I can see so far!
It's going to take me a while to review menu.asm, but I thought I'd submit this now.
I also have not compiled and tested yet.

2021-03-04 22:49 UTC, technobly commented on code/stm32/main.c
> +	if(!settingsReady) {
Nit: `if () {` instead of `if() {`.

2021-03-04 22:49 UTC, technobly commented on code/stm32/main.c
> +	if(settingsReady && isDirectoryExist(settings.directory)) {
Nit: `if () {` instead of `if() {`.

2021-03-04 22:49 UTC, technobly commented on code/stm32/main.c
> +	if(addr >= MENU_MEM_ADDR && addr <= MENU_MEM_ADDR + sizeof(SettingsRecord)) {
Nit: `if () {` instead of `if() {`.

2021-03-04 22:49 UTC, technobly commented on code/stm32/main.c
> +		strcpy(menuDir, "/roms");
strncpy

2021-03-04 22:49 UTC, technobly commented on code/stm32/menu.c
> +	if(res == FR_OK) {
Nit: `if () {` instead of `if() {`.

2021-03-04 22:49 UTC, technobly commented on code/stm32/settings.h
> +// #define MAX_GAME_SCORE_SIZE     (6 + 1)  // Max of 6 ASCII characters + NULL
Leftover cruft? :D

2021-03-04 22:49 UTC, technobly commented on code/stm32/settings.h
> +// @TODO: detect settings structure change and wipe settings file
There should be some magic 4 byte value (e.g. 0xCAF1A77E) added to the struct to help validate/invalidate the data.  If it's not present, the settings can be default initialized.

Another TODO would be to merge the exiting system_options in sys.h with this new settings struct.  It also has a concept of size and version elements.  In the future when we add new elements, we'll update the version and add to the end, so we can detect saved size vs. the sizeof(SettingsRecord) or sizeof(system_options) to know if we have new items to initialize.

2021-03-04 22:49 UTC, technobly commented on code/menu/macro.asm
> +M_LSLD                 macro
I thought Macros didn't compile with asm6809 ?

2021-03-04 22:49 UTC, technobly commented on code/stm32/main.c
> +#define MENU_MEM_ADDR			MENU_DATA_ADDR - 0x140 // 32 bytes reserved for settings data (0x3FC0)
Nitpick: 320 bytes for settings data
Nit: for safety put values in parenthesis for defines: `#define CONST (VALUE)`

2021-03-04 22:49 UTC, technobly commented on code/stm32/romemu.S
> +    mov   r1,#1
if paraRam[254] is not used, this mov line can be omitted.

2021-03-04 22:49 UTC, technobly commented on code/menu/menu.asm
> +  fcb                  "xyz{|}~",$80
😩 Not sure how the whitespace changes crept in everywhere, but it would have been preferred if it wasn't changed all at the same time.  I remember I used Vide to do initial auto-formatting and had spent quite some time setting it up.  Now though, I cannot use Vide for editing so it probably doesn't matter that it's changed.  Just hard to find the code changes.  Github's Ignore whitespace changes does not likely work well on assembly files.

2021-03-05 05:25 UTC, v-kiniv commented on code/stm32/romemu.S
> +    cmp   r8,#0x4000
I think I forget to set it back to 1000 after experiments, will revert.

2021-03-05 05:33 UTC, v-kiniv commented on code/stm32/main.c
> +	uint32_t c = (s->led_red << 16) | (s->led_green << 8) | (s->led_blue << 0);
I have no-buzz installed and had no issues with that. I'd say let people figure out what value works for them.

2021-03-05 05:38 UTC, v-kiniv commented on code/stm32/main.c
> +	const int score_addr = MENU_SYS_ADDR + 0x10;
It's not capital because it's local, and it's not global because it's not used anywhere else. I will change to capital if you wish, but I see no reason to put it in global space.

2021-03-05 05:41 UTC, v-kiniv commented on code/stm32/main.c
> +		strcpy(menuDir, "/roms");
Why? This is null terminated string, hence it will be copied with strcpy with no problems.

2021-03-05 05:41 UTC, v-kiniv commented on code/stm32/settings.h
> +// #define MAX_GAME_SCORE_SIZE     (6 + 1)  // Max of 6 ASCII characters + NULL
Yep

2021-03-05 05:48 UTC, v-kiniv commented on code/stm32/settings.h
> +// @TODO: detect settings structure change and wipe settings file
It was planned, but other things has already taken a lot of time, so in the end I thought I'll be never done with this PR if I will pursue every thing I wanted here. So I will pass this to someone else, at least for now.

2021-03-05 05:49 UTC, v-kiniv commented on code/menu/macro.asm
> +M_LSLD                 macro
Compiles just fine.

2021-03-05 06:00 UTC, v-kiniv commented on code/stm32/main.c
> +#define MENU_MEM_ADDR			MENU_DATA_ADDR - 0x140 // 32 bytes reserved for settings data (0x3FC0)
Yep forgot to update that, but 288, not 320

2021-03-05 06:08 UTC, v-kiniv commented on code/stm32/romemu.S
> +    mov   r1,#1
It's for calling `applyLedSettings` with argument `1`: `applyLedSettings(true)`.
What does the paraRam have to do with it?

2021-03-05 06:22 UTC, v-kiniv commented on code/menu/menu.asm
> +  fcb                  "xyz{|}~",$80
It's changed to make style consistent across all files. And I choose that style(defined in PR description) for the next reasons:

- line does not exceed 80 chars(you can edit it in two pane editor or on small screen)
- macros with arguments fit in
- comments still have enough room

This style:

```
nameloop
                    ldb      cursor                       ;Handle highlighting of active entry
                    cmpb     curpos
                    bne      nohighlight
                    jsr      Intensity_7F
                    bra      hlend
```

waste a lot of space for no reason and does not have room for macros with arguments.

p.s. believe me, I spent not less time bringing it all together to one style.

2021-03-05 23:06 UTC, technobly commented on code/stm32/main.c
> +		strcpy(menuDir, "/roms");
Partly because I already use strncpy in other places for safety and it will reduce the code size if we don't use strcpy anywhere (although I can't say that will be easy, since it might already be used in libopencm3).  It can prevent someone else from copy/pasting some code and using strcpy by accident though.  Also for `settings.directory`.

2021-03-05 23:06 UTC, technobly commented on code/stm32/settings.h
> +// @TODO: detect settings structure change and wipe settings file
Ok, sounds good 👍🏼

2021-03-05 23:07 UTC, technobly commented on code/stm32/main.c
> +	uint32_t c = (s->led_red << 16) | (s->led_green << 8) | (s->led_blue << 0);
It might matter more for the 10 LED v0.2 carts, which I don't think you have.  I will test and see how it goes.

2021-03-05 23:10 UTC, technobly commented on code/stm32/romemu.S
> +    mov   r1,#1
Oh my bad, I had it in my brain that it was calling doHandleEvent.

2021-03-05 23:29 UTC, technobly commented on code/menu/menu.asm
> +  fcb                  "xyz{|}~",$80
In general, whitespace overhaul changes should always be made in separate commits because if we disagree it's a real pain to merge the code changes and then revert the whitespace changes, but mostly makes reviewing difficult.  80 chars is really a dated requirement as most monitors have tons of space these days.  Style was already consistent enough within menu.asm, but no worries... it looks fine in my editor.  I'll probably convert back to 4 spaces for initial opcode tab though (I realize it was 5 before, just a weird Vide requirement which is not necessary anymore).

2021-03-06 08:53 UTC, v-kiniv commented on code/stm32/main.c
> +		strcpy(menuDir, "/roms");
Changed to `strncpy`, but it won't reduce the because it was already used before my changes in `menu.c`. Regarding risk, I think it's the same risk level, if not even worse than `strcpy`, because with `strcpy` you're dealing with a risk of overflow, with `strncpy` you dealing with risk of non-terminated string.

2021-03-19 23:57 UTC, technobly approved these changes

2021-03-20 00:04 UTC, merged